version: "3"

services:
  node:
    build: ./backend
    depends_on:
      - sql
    env_file:
      # Make sure to update this to match your project.
      - abqmural.env
    ports:
      - 8080:4200
    volumes:
      - ./backend/src:/home/node/app/src
      - ./backend/utils:/home/node/app/utils/
      - ./backend/tsconfig.json:/home/node/app/tsconfig.json
  sql:
    build: ./sql
    # Make sure to update this to match your project.
    env_file:
      - abqmural.env
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - compose-lesson:/var/lib/mysql
    ports:
      - 3306:3306
  app:
    build: frontend
    depends_on:
      - node
    #    For deploying to server use ports: - 80:80
    ports:
      - 80:80
volumes:
  compose-lesson:

